### PR TITLE
fixed whitespace not properly escaped in attribute values #11

### PR DESCRIPTION
**Pull request by lucastheisen**

### CODE REVIEW

**Comment by lucastheisen** [comment]
@perigrin , any chance you could merge this pull request and publish a new version?  I really want to avoid setting up my own cpan mirror to force resolution of my version...

**Comment by perigrin** [comment]
I'm out of town. It's next on my todo list though so I'll try to get to it ASAP. Ping me again if you don't see it by Tuesday.

-Chris

**Comment by perigrin** [comment]
Release in 0.57 to CPAN just a few seconds ago.

**Comment by lucastheisen** [comment]
Thank you sir, this cleaned up my CD pipeline 💯

**Pull request merged**
